### PR TITLE
Apply Proofpoint customizations

### PR DESCRIPTION
**Pull request by johngmyers**
Everything else got effectively upstreamed.

Unfortunately, when they upgraded kube-dns to 1.15.13 they forgot to also upgrade k8s-dns-dnsmasq-nanny. I have filed kubernetes/kops#9687 to fix this in 1.18.1. We could take that commit instead, as it upgrades to 1.15.13 instead of 1.15.4.

### CODE REVIEW

**Comment by johngmyers** [comment]
@rajatjindal your opinion? Should we take this or should we cherrypick my PR into the upstream release-1.18 branch?

**Comment by rajatjindal** [comment]
I think our end goal is to start using kops upstream. we can take this commit for now, and then submit for 1.15.4 version upstream and use that once its available.

**Comment by johngmyers** [comment]
Upstream and this branch have 1.15.13 kube-dns. This PR brings nanny up to 1.15.4, same as we had in 1.16. My upstream PR, which is merging now, brings nanny up to 1.15.13.

**Comment by rajatjindal** [comment]
ok. may be we should keep what we have currently deployed for 1.16.x, and move to updated version when we move to 1.17.x?

**Comment by johngmyers** [comment]
We're going to move to kops 1.18 and k8s 1.17.

**Comment by johngmyers** [comment]
This PR is into release-1.18 branch. Nobody's talking about changing release-1.16 branch.

**Comment by rajatjindal** [comment]
we should pick whats in upstream. its newer anyways. we can cherrypick the commit u made to kops

**Comment by johngmyers** [comment]
Closing in favor of #28

**Pull request closed without merging**
